
import java.awt.Color;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author WeSon8840
 */
public class Explain extends javax.swing.JFrame {

    /**
     * Creates new form Explain
     */
    public Explain() {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Step1Label = new javax.swing.JLabel();
        Step2Label = new javax.swing.JLabel();
        Wrong = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Oxygen = new javax.swing.JLabel();
        S2 = new javax.swing.JLabel();
        Ture = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Sulfur = new javax.swing.JLabel();
        S = new javax.swing.JLabel();
        StartButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Step1Label.setFont(new java.awt.Font("Segoe Print", 0, 16)); // NOI18N
        Step1Label.setText("  Step 1: Choose on symbol");

        Step2Label.setFont(new java.awt.Font("Segoe Print", 0, 16)); // NOI18N
        Step2Label.setText("  Step 2: Select the full name of the symbol.");

        Wrong.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Wrong.setForeground(new java.awt.Color(255, 51, 0));

        jLabel8.setFont(new java.awt.Font("SouvenirItcTEELig", 0, 16)); // NOI18N
        jLabel8.setText("Bibi-- You are wrong. Try again!");

        Oxygen.setFont(new java.awt.Font("SouvenirItcTEELig", 0, 16)); // NOI18N
        Oxygen.setText("Oxygen");

        S2.setFont(new java.awt.Font("SouvenirItcTEELig", 0, 16)); // NOI18N
        S2.setText("S");

        javax.swing.GroupLayout WrongLayout = new javax.swing.GroupLayout(Wrong);
        Wrong.setLayout(WrongLayout);
        WrongLayout.setHorizontalGroup(
            WrongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WrongLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(S2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Oxygen)
                .addGap(64, 64, 64))
            .addGroup(WrongLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        WrongLayout.setVerticalGroup(
            WrongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WrongLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(WrongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(S2)
                    .addComponent(Oxygen))
                .addGap(40, 40, 40)
                .addComponent(jLabel8)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        Ture.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("SouvenirItcTEELig", 0, 16)); // NOI18N
        jLabel5.setText("Bingo!  Congratulations.");

        Sulfur.setFont(new java.awt.Font("SouvenirItcTEELig", 0, 16)); // NOI18N
        Sulfur.setText("Sulfur");

        S.setFont(new java.awt.Font("SouvenirItcTEELig", 0, 16)); // NOI18N
        S.setText("S");
        S.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout TureLayout = new javax.swing.GroupLayout(Ture);
        Ture.setLayout(TureLayout);
        TureLayout.setHorizontalGroup(
            TureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TureLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(S)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Sulfur)
                .addGap(54, 54, 54))
            .addGroup(TureLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel5)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        TureLayout.setVerticalGroup(
            TureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TureLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(TureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sulfur)
                    .addComponent(S))
                .addGap(38, 38, 38)
                .addComponent(jLabel5)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        StartButton.setFont(new java.awt.Font("Lint McCree Intl BB", 0, 11)); // NOI18N
        StartButton.setForeground(new java.awt.Color(51, 51, 255));
        StartButton.setText("Let's Start");
        StartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartButtonActionPerformed(evt);
            }
        });

        BackButton.setFont(new java.awt.Font("Lint McCree Intl BB", 0, 11)); // NOI18N
        BackButton.setForeground(new java.awt.Color(51, 51, 255));
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(StartButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Ture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(Wrong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Step2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Step1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(BackButton))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(StartButton)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackButton)
                    .addComponent(Step1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(Step2Label)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Ture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Wrong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartButtonActionPerformed
        new game().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_StartButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        new Inc().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void SMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SMouseClicked

    }//GEN-LAST:event_SMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Explain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Explain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Explain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Explain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Explain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel Oxygen;
    private javax.swing.JLabel S;
    private javax.swing.JLabel S2;
    private javax.swing.JButton StartButton;
    private javax.swing.JLabel Step1Label;
    private javax.swing.JLabel Step2Label;
    private javax.swing.JLabel Sulfur;
    private javax.swing.JPanel Ture;
    private javax.swing.JPanel Wrong;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
