
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JLabel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author WeSon8840
 */
public class game extends javax.swing.JFrame {
    String selected1="",selected2="";
    boolean t=false;
    ArrayList<String> a=new ArrayList<>(),b=new ArrayList<>();
    int selected_long = -1;
    int selected_short = -1;
    JLabel selected_long_label = null;
    JLabel selected_short_label = null;
    String[] longName = {"calcium",
        "fluorine",
        "copper",
        "chlorine",
        "oxygen",
        "nitrogen",
        "sodium",
        "aluminium",
        "potassium",
        "iron",
        "carbon",
        "silver",
        "hydrogen",
        "phosphorus",
        "magnesium"};
    String[] shortName = {"ca",
        "f",
        "cu",
        "cl",
        "o",
        "n",
        "na",
        "al",
        "k",
        "fe",
        "c",
        "ag",
        "h",
        "p",
        "mg"};
    /**
     * Creates new form game
     */
    public game() {
//        a.add("calcium");
//        a.add("fluorine");
//        a.add("copper");
//        a.add("chlorine");
//        a.add("oxrgen");
//        a.add("nitrogen");
//        a.add("sodium");
//        a.add("aluminium");
//        a.add("potassium");
//        a.add("iron");
//        a.add("carbon");
//        a.add("silver");
//        a.add("hydrogen");
//        a.add("phosphorus");
//        a.add("magnesium");
//        b.add("ca");
//        b.add("f");
//        b.add("cu");
//        b.add("cl");
//        b.add("o");
//        b.add("n");
//        b.add("na");
//        b.add("al");
//        b.add("k");
//        b.add("fe");
//        b.add("c");
//        b.add("ag");
//        b.add("h");
//        b.add("p");
//        b.add("mg");
        initComponents();
        getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        H = new javax.swing.JLabel();
        Fe = new javax.swing.JLabel();
        Na = new javax.swing.JLabel();
        Ca = new javax.swing.JLabel();
        K = new javax.swing.JLabel();
        Mg = new javax.swing.JLabel();
        C = new javax.swing.JLabel();
        O = new javax.swing.JLabel();
        N = new javax.swing.JLabel();
        Cl = new javax.swing.JLabel();
        Hydrogen = new javax.swing.JLabel();
        Potassium = new javax.swing.JLabel();
        Sodium = new javax.swing.JLabel();
        Calcium = new javax.swing.JLabel();
        Iron = new javax.swing.JLabel();
        Magnesium = new javax.swing.JLabel();
        Carbon = new javax.swing.JLabel();
        Aluminium = new javax.swing.JLabel();
        Nitrogen = new javax.swing.JLabel();
        Oxygen = new javax.swing.JLabel();
        F = new javax.swing.JLabel();
        Al = new javax.swing.JLabel();
        P = new javax.swing.JLabel();
        Fluorine = new javax.swing.JLabel();
        Chlorine = new javax.swing.JLabel();
        Phosphorus = new javax.swing.JLabel();
        Copper = new javax.swing.JLabel();
        Sliver = new javax.swing.JLabel();
        Ag = new javax.swing.JLabel();
        Cu = new javax.swing.JLabel();
        Tittle = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(580, 500));
        getContentPane().setLayout(null);

        H.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        H.setText("H");
        H.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClicked(evt);
            }
        });
        getContentPane().add(H);
        H.setBounds(257, 185, 13, 26);

        Fe.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        Fe.setText("Fe");
        Fe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClicked(evt);
            }
        });
        getContentPane().add(Fe);
        Fe.setBounds(456, 126, 22, 26);

        Na.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        Na.setText("Na");
        Na.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClicked(evt);
            }
        });
        getContentPane().add(Na);
        Na.setBounds(119, 95, 23, 26);

        Ca.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        Ca.setText("Ca");
        Ca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClicked(evt);
            }
        });
        getContentPane().add(Ca);
        Ca.setBounds(339, 242, 23, 26);

        K.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        K.setText("K");
        K.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClicked(evt);
            }
        });
        getContentPane().add(K);
        K.setBounds(491, 376, 13, 26);

        Mg.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        Mg.setText("Mg");
        Mg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClicked(evt);
            }
        });
        getContentPane().add(Mg);
        Mg.setBounds(162, 244, 26, 26);

        C.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        C.setText("C");
        C.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClicked(evt);
            }
        });
        getContentPane().add(C);
        C.setBounds(447, 330, 13, 26);

        O.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        O.setText("O");
        O.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClicked(evt);
            }
        });
        getContentPane().add(O);
        O.setBounds(419, 167, 14, 26);

        N.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        N.setText("N");
        N.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClicked(evt);
            }
        });
        getContentPane().add(N);
        N.setBounds(91, 330, 13, 26);

        Cl.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        Cl.setText("Cl");
        Cl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClicked(evt);
            }
        });
        getContentPane().add(Cl);
        Cl.setBounds(138, 293, 18, 26);

        Hydrogen.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        Hydrogen.setText("Hydrogen");
        Hydrogen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClicked(evt);
            }
        });
        getContentPane().add(Hydrogen);
        Hydrogen.setBounds(290, 318, 86, 26);

        Potassium.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        Potassium.setText("Potassium");
        Potassium.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClicked(evt);
            }
        });
        getContentPane().add(Potassium);
        Potassium.setBounds(220, 225, 92, 26);

        Sodium.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        Sodium.setText("Sodium");
        Sodium.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClicked(evt);
            }
        });
        getContentPane().add(Sodium);
        Sodium.setBounds(175, 185, 67, 26);

        Calcium.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        Calcium.setText("Calcium");
        Calcium.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClicked(evt);
            }
        });
        getContentPane().add(Calcium);
        Calcium.setBounds(175, 63, 71, 26);

        Iron.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        Iron.setText("Iron");
        Iron.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClicked(evt);
            }
        });
        getContentPane().add(Iron);
        Iron.setBounds(204, 270, 34, 26);

        Magnesium.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        Magnesium.setText("Magnesium");
        Magnesium.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClicked(evt);
            }
        });
        getContentPane().add(Magnesium);
        Magnesium.setBounds(290, 376, 101, 26);

        Carbon.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        Carbon.setText("Carbon");
        Carbon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClicked(evt);
            }
        });
        getContentPane().add(Carbon);
        Carbon.setBounds(290, 270, 63, 26);

        Aluminium.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        Aluminium.setText("Aluminium");
        Aluminium.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClicked(evt);
            }
        });
        getContentPane().add(Aluminium);
        Aluminium.setBounds(288, 185, 95, 26);

        Nitrogen.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        Nitrogen.setText("Nitrogen");
        Nitrogen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClicked(evt);
            }
        });
        getContentPane().add(Nitrogen);
        Nitrogen.setBounds(288, 146, 75, 26);

        Oxygen.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        Oxygen.setText("Oxygen");
        Oxygen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClicked(evt);
            }
        });
        getContentPane().add(Oxygen);
        Oxygen.setBounds(175, 146, 69, 26);

        F.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        F.setText("F");
        F.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClicked(evt);
            }
        });
        getContentPane().add(F);
        F.setBounds(419, 90, 11, 26);

        Al.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        Al.setText("Al");
        Al.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClicked(evt);
            }
        });
        getContentPane().add(Al);
        Al.setBounds(394, 280, 18, 26);

        P.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        P.setText("P");
        P.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClicked(evt);
            }
        });
        getContentPane().add(P);
        P.setBounds(50, 376, 12, 26);

        Fluorine.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        Fluorine.setText("Fluorine");
        Fluorine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClicked(evt);
            }
        });
        getContentPane().add(Fluorine);
        Fluorine.setBounds(290, 70, 72, 26);

        Chlorine.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        Chlorine.setText("Chlorine");
        Chlorine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClicked(evt);
            }
        });
        getContentPane().add(Chlorine);
        Chlorine.setBounds(288, 106, 74, 26);

        Phosphorus.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        Phosphorus.setText("Phosphorus");
        Phosphorus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClicked(evt);
            }
        });
        getContentPane().add(Phosphorus);
        Phosphorus.setBounds(138, 376, 105, 26);

        Copper.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        Copper.setText("Copper");
        Copper.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClicked(evt);
            }
        });
        getContentPane().add(Copper);
        Copper.setBounds(175, 106, 64, 26);

        Sliver.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        Sliver.setText("Silver");
        Sliver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClicked(evt);
            }
        });
        getContentPane().add(Sliver);
        Sliver.setBounds(188, 318, 51, 26);

        Ag.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        Ag.setText("Ag");
        Ag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClicked(evt);
            }
        });
        getContentPane().add(Ag);
        Ag.setBounds(79, 134, 24, 26);

        Cu.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        Cu.setText("Cu");
        Cu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClicked(evt);
            }
        });
        getContentPane().add(Cu);
        Cu.setBounds(119, 176, 24, 26);

        Tittle.setFont(new java.awt.Font("Nueva Std", 0, 22)); // NOI18N
        Tittle.setText("Find my Brother ! !");
        getContentPane().add(Tittle);
        Tittle.setBounds(10, 11, 177, 31);

        BackButton.setFont(new java.awt.Font("Lint McCree Intl BB", 0, 11)); // NOI18N
        BackButton.setForeground(new java.awt.Color(0, 51, 204));
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackButton);
        BackButton.setBounds(464, 12, 57, 25);

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseClicked
//        try{
        JLabel label = (JLabel) evt.getSource();
//        if(label == null)
//            return;
        
        String labelText = label.getText();
        
        
        int ii = 0;
        if(labelText.length()>2)
        {   
            // long
            while(ii<longName.length){
                if( longName[ii].compareToIgnoreCase(labelText)==0)
                    break;
                ii ++;
            }
            
            if(!t) {
                 label.setForeground(Color.RED);
                 selected_long = ii;
                 selected_long_label = label;
                 t  = true;
            }
            else
            {
                if(selected_long >=0)
                {
                    selected_long_label.setForeground(Color.BLACK);
                    selected_long = -1;
                    selected_long_label = null;
                    t = false;
                }
                else
                {
                    if(selected_short == ii)
                    {
                        selected_short_label.setVisible(false);
                        selected_short_label.setEnabled(false);
                        //selected_short_label.setText("");
                        label.setVisible(false);
                        label.setEnabled(false);
                        t = false;
                    }
                    else
                    {
                        selected_short_label.setForeground(Color.BLACK);
                        selected_short = -1;
                        selected_short_label = null;
                        t = false;
                    }
                }
            }
        }
        else
        {
            while(ii<shortName.length) {
               if(shortName[ii].compareToIgnoreCase(labelText)==0)
                   break;
               ii++;
            }
            if(!t)
            {
                label.setForeground(Color.RED);
                selected_short = ii;
                selected_short_label =label;
                t = true;
            }
            else
            {
                if(selected_short >=0)
                {
                    selected_short_label.setForeground(Color.BLACK);
                    selected_short = -1;
                    selected_short_label = null;
                    t = false;
                }
                else
                {
                    if(ii == selected_long)
                    {
                        selected_long_label.setVisible(false);
                        selected_long_label.setEnabled(false);
                        label.setVisible(false);
                        label.setEnabled(false);
                        t = false;
                    }
                    else
                    {
                        selected_long_label.setForeground(Color.BLACK);
                        selected_long_label = null;
                        selected_long = -1;
                        t = false;
                    }
                }
            }
        }
//        }
//        catch(Exception e)
//        {}
//        if(label.getForeground().equals(Color.BLACK))
//            label.setForeground(Color.RED);
//        else
//            label.setForeground(Color.BLACK);
        
//        if(!t){
//            t=true;
//            selected1="calcium";
//            Calcium.setForeground(new Color(255,0,0));
//        }else{
//            if(selected1=="calcium"){
//                selected1="";
//                Calcium.setForeground(new Color(0,0,0));
//            }else{
//                selected2="calcium";
//                if(check()){
//                    Calcium.setText("");
//                    Ca.setText("");
//                }else{
//                    Calcium.setForeground(new Color(0,0,0));
//                    Ca.setForeground(new Color(0,0,0));
//                }
//            }
//            t=false;
//        }
    }//GEN-LAST:event_MouseClicked

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        new Inc().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackButtonActionPerformed
//    public boolean check(){
//        int m,n;
//        if(a.indexOf(selected1)>=0){
//            m=a.indexOf(selected1);
//            n=b.indexOf(selected2);
//        }else{
//            m=a.indexOf(selected2);
//            n=b.indexOf(selected1);
//        }
//        return m==n;
//    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ag;
    private javax.swing.JLabel Al;
    private javax.swing.JLabel Aluminium;
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel C;
    private javax.swing.JLabel Ca;
    private javax.swing.JLabel Calcium;
    private javax.swing.JLabel Carbon;
    private javax.swing.JLabel Chlorine;
    private javax.swing.JLabel Cl;
    private javax.swing.JLabel Copper;
    private javax.swing.JLabel Cu;
    private javax.swing.JLabel F;
    private javax.swing.JLabel Fe;
    private javax.swing.JLabel Fluorine;
    private javax.swing.JLabel H;
    private javax.swing.JLabel Hydrogen;
    private javax.swing.JLabel Iron;
    private javax.swing.JLabel K;
    private javax.swing.JLabel Magnesium;
    private javax.swing.JLabel Mg;
    private javax.swing.JLabel N;
    private javax.swing.JLabel Na;
    private javax.swing.JLabel Nitrogen;
    private javax.swing.JLabel O;
    private javax.swing.JLabel Oxygen;
    private javax.swing.JLabel P;
    private javax.swing.JLabel Phosphorus;
    private javax.swing.JLabel Potassium;
    private javax.swing.JLabel Sliver;
    private javax.swing.JLabel Sodium;
    private javax.swing.JLabel Tittle;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
